mysite/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from project.views import *
from django.conf.urls.static import static
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('', main, name='main'),
    path('administrator/', administrator, name='administrator'),
    path('active/', active, name='active'),
    path('client_orders/', client_orders, name='client_orders'),
    path('add/category/', add_category, name='add_category'),
    path('edit/category/<int:category_id>/', edit_category, name='edit_category'),
    path('delete_category/<int:category_id>/', delete_category, name='delete_category'),
    path('add/advert/', add_advert, name='add_advert'),
    path('edit/advert/<int:advert_id>/', edit_advert, name='edit_advert'),
    path('delete_advert/<int:advert_id>/', delete_advert, name='delete_advert'),
    path('add/producer/', add_producer, name='add_producer'),
    path('edit/producer/<int:producer_id>/', edit_producer, name='edit_producer'),
    path('delete_producer/<int:producer_id>/', delete_producer, name='delete_producer'),
    path('add/product/', add_product, name='add_product'),
    path('create/', create_order, name='create_order'),
    path('admin_orders/', admin_orders, name='admin_orders'),
    path('order_detail/<int:order_id>/', order_detail, name='order_detail'),
    path('delete_order/<int:order_id>/', delete_order, name='delete_order'),
    path('order/<int:order_id>/', order_detail, name='order_detail'),
    path('reviews/', review_list, name='review_list'),
    path('add/review/<int:product_id>/', add_review, name='add_review'),
    path('product/<int:product_id>/', product_detail, name='product_detail'),
    path('product/<int:product_id>/edit/', product_edit, name='product_edit'),
    path('product/<int:product_id>/delete/', product_delete, name='product_delete'),
    path('favorites/', favorite_list, name='favorite_list'),
    path('add_to_favorites/<int:product_id>/', add_to_favorites, name='add_to_favorites'),
    path('add_to_cart/<int:product_id>/', add_to_cart, name='add_to_cart'),
    path('cart/', cart, name='cart'),
    path('remove_from_cart/<int:product_id>/', remove_from_cart, name='remove_from_cart'),
    path('ordering/', ordering, name='ordering'),
    path('register/', registration_view, name='register'),
    path('products/<int:category_id>/', product_list, name='product_list'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += [
        re_path(
            r"^media/(?P<path>.*)$",
            serve,
            {
                "document_root": settings.MEDIA_ROOT,
            },
        ),
    ]

project/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone

# Create your models here.
class Category(models.Model):
    name = models.CharField("Название категории", max_length=255, unique=True)

    class Meta:
        verbose_name_plural = "Категории"

    def __str__(self):
        return self.name

class Advert(models.Model):
    heading = models.CharField("Заголовок", max_length=255)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="Категория")
    photo = models.FileField("Фото товара", upload_to="adv/")
    date = models.DateField(verbose_name="Дата")

    class Meta:
        verbose_name_plural = "Реклама"

    def __str__(self):
        return self.heading


class Producer(models.Model):
    name = models.CharField("Название производителя", max_length=255)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="Категория")
    description = models.TextField("Описание производителя")
    photo = models.FileField("Фото", upload_to="photos/")

    class Meta:
        verbose_name_plural = "Производители"

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField("Название товара", max_length=255)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="Категория")
    article = models.CharField("Артикул товара", max_length=50, unique=True, blank=True)
    photo = models.FileField("Фото товара", upload_to="product_photos/")
    producer = models.ForeignKey(Producer, on_delete=models.CASCADE, verbose_name="Производитель")
    price = models.DecimalField("Цена", max_digits=10, decimal_places=0)
    description = models.TextField("Описание товара")
    instruction = models.FileField("Инструкция по использованию", upload_to="instructions/", blank=True, null=True)
    quantity = models.PositiveIntegerField("Количество на складе")
    recipe_required = models.BooleanField("Требуется рецепт", default=False)
    in_stock = models.BooleanField("В наличии", default=True)

    class Meta:
        verbose_name_plural = "Препараты"

    def __str__(self):
        return f'{self.name}-{self.article}'

class Review(models.Model):
    subject = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    feedback = models.TextField("Отзыв")
    stars = models.PositiveIntegerField("Оценка", default=5)
    

    class Meta:
        verbose_name_plural = "Отзывы"

class Favorite(models.Model):
    subject = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = "Избранное"

class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    products = models.ManyToManyField(Product, through='CartProduct')
    
    class Meta:
        verbose_name_plural = "Корзина"

    def __str__(self):
        return f"Cart for {self.user}"

class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    class Meta:
        verbose_name_plural = "Компонент корзины"

    def __str__(self):
        return f"{self.quantity} шт x {self.product.name} в {self.cart}"

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=255, null=True, verbose_name = "Ф.И.О")
    phone_number = models.CharField(max_length=20, null=True, verbose_name = "Номер телефона")
    email = models.EmailField(null=True, verbose_name = "Email")
    delivery_address = models.CharField(max_length=255, null=True)
    recipe = models.FileField("Рецепт", upload_to="recipe_photos/", null=True)
    comments = models.TextField(blank=True, null=True, verbose_name = "Комментарий")
    PAYMENT_CHOICES = [
        ('kaspi', 'Выставить счет в Kaspi'),
        ('card', 'Банковская карта'),
        ('cash', 'Наличными курьеру'),
    ]
    payment_method = models.CharField(max_length=20, choices=PAYMENT_CHOICES, verbose_name="Способ оплаты", blank=True, null=True)
    date_created = models.DateTimeField(default=timezone.now, null=True, verbose_name = "Дата заказа")
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0, verbose_name = "Итоговая сумма")
    STATUS_CHOICES = [
        ('processing', 'В обработке'),
        ('accepted', 'Принят'),
        ('canceled', 'Отменен'),
        ('done', 'Доставлен')
    ]
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='processing', verbose_name = "Статус")

    def __str__(self):
        return f"Заказ #{self.id} от {self.full_name}"

class OrderProduct(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    class Meta:
        verbose_name_plural = "Заказ"

    def __str__(self):
        return f"{self.quantity} шт x {self.product.name} в заказе {self.order}"

project/views.py
from django.shortcuts import render

from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login
from django.contrib import messages
from .models import *
from .forms import *
from django.db.models import Q
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count, Max, Min, Avg


def main(request):
    categories = Category.objects.all()
    latest_adverts = Advert.objects.order_by('-date')[:3]
    return render(request, 'main.html', {'categories': categories, 'latest_adverts': latest_adverts})

# Create your views here.
def registration_view(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('main')
    else:
        form = RegistrationForm()

    return render(request, 'registration/register.html', {'form': form})

def administrator(request):
    categories = Category.objects.all()
    categories_stats = Category.objects.annotate(
        product_count=Count('product'),
        max_price=Max('product__price'),
        min_price=Min('product__price'),
        review_count=Count('product__review'),
        avg_stars=Avg('product__review__stars')
    )
    context = {'categories_stats': categories_stats,
               'categories': categories}
    return render(request, 'administrator.html', context)

def active(request):
    categories = Category.objects.all()
    return render(request, 'active.html', {'categories': categories})

def product_list(request, category_id):
    categories = Category.objects.all()
    category = get_object_or_404(Category, id=category_id)
    manufacturers = Producer.objects.all()
    products = Product.objects.filter(category=category)

    # Existing filters
    manufacturer_id = request.GET.get('manufacturer')
    if manufacturer_id:
        products = products.filter(producer_id=manufacturer_id)

    max_price = request.GET.get('price')
    if max_price:
        products = products.filter(price__lte=max_price)

    # New filters
    if 'recipe_required' in request.GET:
        products = products.filter(recipe_required=True)

    if 'in_stock' in request.GET:
        products = products.filter(in_stock=True)
    
    paginator = Paginator(products, 6)  # Show 6 products per page
    page = request.GET.get('page')

    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)

    return render(request, 'product_list.html', {
        'categories': categories,
        'category': category,  # Pass the category to the template
        'manufacturers': manufacturers,
        'products': products,
    })

@login_required
def product_detail(request, product_id):
    categories = Category.objects.all()
    product = get_object_or_404(Product, id=product_id)
    reviews = Review.objects.filter(subject=product)
    is_favorite = Favorite.objects.filter(subject=product, user=request.user).exists()

    return render(request, 'product_detail.html', {'categories': categories, 'product': product, 'reviews': reviews, 'is_favorite': is_favorite})

def product_edit(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return redirect('product_list', category_id=product.category.id)
    else:
        form = ProductForm(instance=product)
    return render(request, 'product_edit.html', {'form': form, 'product': product})

def product_delete(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    category_id = product.category.id
    product.delete()
    return redirect('product_list', category_id=category_id)

@login_required
def favorite_list(request):
    favorites = Favorite.objects.filter(user=request.user)
    products = [favorite.subject for favorite in favorites]

    # Convert the list to a queryset
    product_queryset = Product.objects.filter(id__in=[product.id for product in products])

    # Get all categories and producers
    all_categories = Category.objects.all()
    all_producers = Producer.objects.all()

    # Apply filters
    category_id = request.GET.get('category')
    manufacturer_id = request.GET.get('manufacturer')
    max_price = request.GET.get('price')
    prescription_required = request.GET.get('recipe_required')
    in_stock = request.GET.get('in_stock')

    if category_id:
        product_queryset = product_queryset.filter(category_id=category_id)

    if manufacturer_id:
        product_queryset = product_queryset.filter(producer_id=manufacturer_id)

    if max_price:
        product_queryset = product_queryset.filter(price__lte=max_price)

    if prescription_required:
        product_queryset = product_queryset.filter(recipe_required=True)

    if in_stock:
        product_queryset = product_queryset.filter(in_stock=True)

    return render(request, 'favorites.html', {'products': product_queryset, 'all_categories': all_categories, 'all_producers': all_producers})

@login_required
def add_to_favorites(request, product_id):
    product = get_object_or_404(Product, id=product_id)

    # Проверяем, не добавлен ли уже товар в избранное
    if not Favorite.objects.filter(subject=product, user=request.user).exists():
        Favorite.objects.create(subject=product, user=request.user)

    return redirect('product_list', category_id=product.category.id)

def review_list(request):
    categories = Category.objects.all()
    reviews = Review.objects.filter(user=request.user)
    return render(request, 'review_list.html', {'categories': categories, 'reviews': reviews})

@login_required
def add_review(request, product_id):
    product = get_object_or_404(Product, id=product_id)

    if request.method == 'POST':
        feedback = request.POST.get('feedback')
        stars = request.POST.get('stars')
        
        Review.objects.create(subject=product, user=request.user, feedback=feedback, stars=stars)

    return redirect('product_detail', product_id=product_id)

def create_order(request):
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            order.user = request.user
            order.save()
            return redirect('order_detail', order_id=order.id)
    else:
        form = OrderForm()

    return render(request, 'create_order.html', {'form': form})


def add_category(request):
    categories = Category.objects.all()
    paginator = Paginator(categories, 6)
    page = request.GET.get('page')
    try:
        categories = paginator.page(page)
    except PageNotAnInteger:
        categories = paginator.page(1)
    except EmptyPage:
        categories = paginator.page(paginator.num_pages)
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(request.path_info)
    else:
        form = CategoryForm()

    return render(request, 'add_category.html', {'form': form, 'categories': categories,})

def edit_category(request, category_id):
    categories = Category.objects.all()
    category = get_object_or_404(Category, pk=category_id)
    if request.method == 'POST':
        form = CategoryForm(request.POST, instance=category)
        if form.is_valid():
            form.save()
            return redirect('add_category')
    else:
        form = CategoryForm(instance=category)
    return render(request, 'category_edit.html', {'form': form, 'category': category, 'categories': categories})

def delete_category(request, category_id):
    category = get_object_or_404(Category, id=category_id)
    category.delete()
    return redirect('add_category')

def add_advert(request):
    categories = Category.objects.all()
    adverts = Advert.objects.all()
    if request.method == 'POST':
        form = AdvertForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(request.path_info)
    else:
        form = AdvertForm()

    return render(request, 'add_advert.html', {'form': form, 'adverts': adverts, 'categories': categories,})

def edit_advert(request, advert_id):
    categories = Category.objects.all()
    advert = get_object_or_404(Advert, pk=advert_id)
    if request.method == 'POST':
        form = AdvertForm(request.POST, request.FILES, instance=advert)
        if form.is_valid():
            form.save()
            return redirect('add_advert')
    else:
        form = AdvertForm(instance=advert)

    return render(request, 'advert_edit.html', {'form': form, 'advert': advert, 'categories': categories})

def delete_advert(request, advert_id):
    advert= get_object_or_404(Advert, id=advert_id)
    advert.delete()
    return redirect('add_advert')

def add_producer(request):
    categories = Category.objects.all()
    producers = Producer.objects.all()
    if request.method == 'POST':
        form = ProducerForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(request.path_info)
    else:
        form = ProducerForm()

    return render(request, 'add_producer.html', {'form': form, 'producers': producers, 'categories': categories})

def edit_producer(request, producer_id):
    categories = Category.objects.all()
    producer = get_object_or_404(Producer, pk=producer_id)
    if request.method == 'POST':
        form = ProducerForm(request.POST, request.FILES, instance=producer)
        if form.is_valid():
            form.save()

project/templates/active.html
{% extends 'head.html' %}

{% block nav_block %}
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      Продукция
    </a>
    <ul class="dropdown-menu">
      {% if user.is_authenticated %}
        {% for category in categories %}
          <li><a class="dropdown-item" href="{% url 'product_list' category.id %}">{{ category.name }}</a></li>
        {% endfor %}
      {% else %}
        {% for category in categories %}
        <li><a class="dropdown-item" href="{% url 'login' %}">{{ category.name }}</a></li>
        {% endfor %}
      {% endif %}
    </ul>
  </li>
  
  <li class="nav-item">
      <a class="nav-link" href="#"></a>
  </li>
  {% if user.is_authenticated %}
  <li class="nav-item">
    <a class="nav-link" href="{% url 'client_orders' %}">Мои заявки</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'favorite_list' %}">Избранное</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'review_list' %}">Мои отзывы</a>
  </li>
    <!-- Если пользователь авторизован -->
    {% if user.is_active and user.is_staff %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'administrator' %}">{{ user.username }}</a>
      </li>
    {% elif user.is_active %}
    <li class="nav-item">           
      <a class="nav-link" href="{% url 'cart' %}"><i class="bi bi-cart-plus-fill bi-5x"></i> Корзина </a>
    </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'active' %}">{{ user.username }}</a>
      </li>
    {% endif %}
    <li class="nav-item">
      <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
    </li>
  {% else %}
    <!-- Если пользователь не авторизован -->
    <li class="nav-item">
      <a class="nav-link" href="{% url 'login' %}">Войти</a>
    </li>
  {% endif %}
{% endblock %}

{% block content %}
  <div class="container mt-4">
    <div class="row text-center">
      <div class="col-md-12">
        <i class="bi bi-person-fill display-1 text-primary"></i>
        <br>
        <!-- User details -->
        <h2>Добро пожаловать: {{ user.username }} !</h2>
        <p>Ваше Ф.И.О.: {{ user.first_name }} {{ user.last_name }}</p>
        <p>Email: {{ user.email }}</p>
      </div>
    </div>
  </div>

<br>
<br>
{% endblock %}

project/templates/add_advert.html
{% extends 'head.html' %}

{% block nav_block %}
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      Продукция
    </a>
    <ul class="dropdown-menu">
      {% if user.is_authenticated %}
        {% for category in categories %}
          <li><a class="dropdown-item" href="{% url 'product_list' category.id %}">{{ category.name }}</a></li>
        {% endfor %}
      {% else %}
        {% for category in categories %}
        <li><a class="dropdown-item" href="{% url 'login' %}">{{ category.name }}</a></li>
        {% endfor %}
      {% endif %}
    </ul>
  </li>
  
  <li class="nav-item">
      <a class="nav-link" href="#"></a>
  </li>
  {% if user.is_authenticated %}
    <!-- Если пользователь авторизован -->
    {% if user.is_active and user.is_staff %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Панель управления
        </a>
        <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'add_product' %}">Препараты</a></li>
              <li><a class="dropdown-item" href="{% url 'add_category' %}">Категории</a></li>
              <li><a class="dropdown-item" href="{% url 'add_producer' %}">Производители</a></li>
              <li><a class="dropdown-item" href="{% url 'add_advert' %}">Реклама</a></li>
        </ul>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'admin_orders' %}">Обработка заявок</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'administrator' %}">{{ user.username }}</a>
      </li>
    {% elif user.is_active %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'active' %}">{{ user.username }}</a>
      </li>
    {% endif %}
    <li class="nav-item">
      <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
    </li>
  {% else %}
    <!-- Если пользователь не авторизован -->
    <li class="nav-item">
      <a class="nav-link" href="{% url 'login' %}">Войти</a>
    </li>
  {% endif %}
{% endblock %}


{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col-md-6">
            <h2>Добавить баннер</h2>
            <form method="POST" action="{% url 'add_advert' %}" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Добавить</button>
            </form>
        </div>

        <!-- List of Added Categories -->
        <div class="col-md-6">
            <h2>Все баннеры: </h2>
            <br>
            {% for adv in adverts %}
                <div class="card mb-2">
                    <div class="card-body">
                        <h5 class="card-title">{{ adv.heading }}</h5>
                        <!-- Add Edit and Delete Buttons (placeholders for now) -->
                        <a href="{% url 'edit_advert' adv.id %}" class="btn btn-warning">
                          <i class="bi bi-pencil"></i> Редактировать
                        </a>
                      
                        <a href="{% url 'delete_advert' adv.id %}" class="btn btn-danger">
                          <i class="bi bi-trash"></i> Удалить
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

project/templates/client_orders.html
{% extends 'head.html' %}
{% load static %}

{% block nav_block %}
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      Продукция
    </a>
    <ul class="dropdown-menu">
      {% if user.is_authenticated %}
        {% for category in categories %}
          <li><a class="dropdown-item" href="{% url 'product_list' category.id %}">{{ category.name }}</a></li>
        {% endfor %}
      {% else %}
        {% for category in categories %}
        <li><a class="dropdown-item" href="{% url 'login' %}">{{ category.name }}</a></li>
        {% endfor %}
      {% endif %}
    </ul>
  </li>
  
  <li class="nav-item">
      <a class="nav-link" href="#"></a>
  </li>
  {% if user.is_authenticated %}
  <li class="nav-item">
    <a class="nav-link" href="{% url 'client_orders' %}">Мои заявки</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'favorite_list' %}">Избранное</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="{% url 'review_list' %}">Мои отзывы</a>
  </li>
    <!-- Если пользователь авторизован -->
    {% if user.is_active and user.is_staff %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'administrator' %}">{{ user.username }}</a>
      </li>
    {% elif user.is_active %}
    <li class="nav-item">           
      <a class="nav-link" href="{% url 'cart' %}"><i class="bi bi-cart-plus-fill bi-5x"></i> Корзина </a>
    </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'active' %}">{{ user.username }}</a>
      </li>
    {% endif %}
    <li class="nav-item">
      <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
    </li>
  {% else %}
    <!-- Если пользователь не авторизован -->
    <li class="nav-item">
      <a class="nav-link" href="{% url 'login' %}">Войти</a>
    </li>
  {% endif %}
{% endblock %}
{% block content %}
<br>
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item">Препараты</li>
    <li class="breadcrumb-item">Мои заказы</li>
  </ol>
</nav>
<h1>Ваши заказы</h1>
<br>
    
  {% if orders %}
    <table class="table table-striped table-bordered">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Дата создания</th>
          <th scope="col">Товары</th>
          <th scope="col">Сумма</th>
          <th scope="col">Статус заказа</th>
          
        </tr>
      </thead>
      <tbody>
        {% for order in orders %}
          <tr>
            <th scope="row">{{ forloop.counter }}</th>
            <td>{{ order.date_created|date:"d/m/Y" }}</td>
            <td>
              <ul>
                {% for order_product in order.orderproduct_set.all %}
                  <li>{{ order_product.product.name }} - {{ order_product.quantity }} шт.</li>
                {% endfor %}
              </ul>
            </td>
            <td>{{ order.total_price|floatformat:0 }}</td>
            <td>{{ order.get_status_display }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p>У вас пока нет заказов.</p>
  {% endif %}

{% endblock %}

project/templates/create_order.html
{% extends 'head.html' %}

{% block content %}
  <h2>Create Order</h2>
  <form method="post" action="{% url 'create_order' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit Order</button>
  </form>
{% endblock %}

project/templates/producer_edit.html
{% extends 'head.html' %}

{% block nav_block %}
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
      Продукция
    </a>
    <ul class="dropdown-menu">
      {% if user.is_authenticated %}
        {% for category in categories %}
          <li><a class="dropdown-item" href="{% url 'product_list' category.id %}">{{ category.name }}</a></li>
        {% endfor %}
      {% else %}
        {% for category in categories %}
        <li><a class="dropdown-item" href="{% url 'login' %}">{{ category.name }}</a></li>
        {% endfor %}
      {% endif %}
    </ul>
  </li>
  
  <li class="nav-item">
      <a class="nav-link" href="#"></a>
  </li>
  {% if user.is_authenticated %}
    <!-- Если пользователь авторизован -->
    {% if user.is_active and user.is_staff %}
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Панель управления
        </a>
        <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{% url 'add_product' %}">Препараты</a></li>
              <li><a class="dropdown-item" href="{% url 'add_category' %}">Категории</a></li>
              <li><a class="dropdown-item" href="{% url 'add_producer' %}">Производители</a></li>
              <li><a class="dropdown-item" href="{% url 'add_advert' %}">Реклама</a></li>
        </ul>
      </li>

      <li class="nav-item">
        <a class="nav-link" href="{% url 'admin_orders' %}">Обработка заявок</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'administrator' %}">{{ user.username }}</a>
      </li>
    {% elif user.is_active %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'active' %}">{{ user.username }}</a>
      </li>
    {% endif %}
    <li class="nav-item">
      <a class="nav-link" href="{% url 'logout' %}">Выйти</a>
    </li>
  {% else %}
    <!-- Если пользователь не авторизован -->
    <li class="nav-item">
      <a class="nav-link" href="{% url 'login' %}">Войти</a>
    </li>
  {% endif %}
{% endblock %}

{% block content %}
<br>
  <h2>Редактировать производителя</h2>
  <form method="post" enctype="multipart/form-data" action="{% url 'edit_producer' producer.id %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-primary" type="submit">Сохранить</button>
  </form>
{% endblock %}